# Generated by Django 5.1.3 on 2024-11-13 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_showproducer_email_showproducer_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomerUser",
            new_name="Customer",
        ),
    ]
