server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /etc/promtail/positions.yaml  # Tracks the last read position in log files

scrape_configs:
  - job_name: django_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          app: concert_hall_booking
          log_level: debug
          __path__: /var/log/application.log  # Path inside Promtail container
