# Generated by Django 5.1.2 on 2024-11-09 16:21

import django.db.models.deletion
import show_manager.models
import show_manager.showstatuses
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hall_manager", "0001_initial"),
        ("users", "0002_remove_showproducer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("MORNING", "MORNING"),
                            ("NOON", "NOON"),
                            ("EVENING", "EVENING"),
                            ("NIGHT", "NIGHT"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LIVE_PERFORMANCE", "LIVE_PERFORMANCE"),
                            ("MOVIE_SCREENING", "MOVIE_SCREENING"),
                            ("CONFERENCE", "CONFERENCE"),
                        ],
                        default=show_manager.models.ShowCategory["LIVE_PERFORMANCE"],
                        max_length=20,
                    ),
                ),
                ("has_intermission", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("COMPLETED", "COMPLETED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default=show_manager.showstatuses.ShowStatusEnum["PENDING"],
                        max_length=10,
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="hall_manager.hall",
                    ),
                ),
                (
                    "show_producer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="users.showproducer",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="show_manager.slot",
                    ),
                ),
            ],
        ),
    ]
