# Generated by Django 5.1.2 on 2024-11-14 12:23

import django.db.models.deletion
import shared.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hall_manager", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("has_intermission", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SCHEDULED", "SCHEDULED"),
                            ("COMPLETED", "COMPLETED"),
                            ("REJECTED", "REJECTED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="hall_manager.category",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="hall_manager.hall",
                    ),
                ),
                (
                    "show_producer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shows",
                        to="users.showproducer",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="hall_manager.slot",
                    ),
                ),
            ],
            bases=(models.Model, shared.interfaces.Subject),
        ),
    ]
