# Generated by Django 5.1.2 on 2024-11-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hall_manager", "0005_remove_hallsupportscategory_hall_id_and_more"),
        ("show_manager", "0003_remove_show_slot_remove_show_hall_and_more"),
        ("users", "0003_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="hall",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="hall_manager.hall",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="show_producer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shows",
                to="users.showproducer",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="hall_manager.slot",
            ),
        ),
    ]
