# Generated by Django 5.1.2 on 2024-11-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hall_manager",
            "0010_category_remove_hallsupportscategory_show_category_and_more",
        ),
        ("show_manager", "0004_show_hall_show_show_producer_show_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shows",
                to="hall_manager.category",
            ),
        ),
    ]
