# Generated by Django 5.1.2 on 2024-11-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermembership',
            old_name='membershipCode',
            new_name='membership_type',
        ),
    ]
