# Generated by Django 5.1.2 on 2024-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_customermembership_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='expiry',
            field=models.DateTimeField(blank=True),
        ),
    ]
