# Generated by Django 5.1.2 on 2024-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_customermembership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
