# Generated by Django 5.1.2 on 2024-12-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_customermembership_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customermembership',
            name='membership_type',
            field=models.CharField(default='REGULAR', max_length=10),
        ),
    ]
