# Generated by Django 5.1.2 on 2024-11-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hall_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(
                choices=[("REGULAR", "REGULAR"), ("PREMIUM", "PREMIUM")],
                default="REGULAR",
                max_length=10,
            ),
        ),
    ]
