# Generated by Django 5.1.2 on 2024-11-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_manager', '0002_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timing', models.CharField(choices=[('MORNING', 'MORNING'), ('NOON', 'NOON'), ('EVENING', 'EVENING'), ('NIGHT', 'NIGHT')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=30)),
                ('location', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HallSupportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_category', models.CharField(choices=[('LIVE_PERFORMANCE', 'LIVE_PERFORMANCE'), ('MOVIE_SCREENING', 'MOVIE_SCREENING'), ('CONFERENCE', 'CONFERENCE')], default='LIVE_PERFORMANCE', max_length=20)),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_manager.hall')),
            ],
        ),
        migrations.CreateModel(
            name='HallSupportsSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_manager.hall')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_manager.slot')),
            ],
        ),
    ]
