# Generated by Django 5.1.2 on 2024-11-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hall_manager", "0003_slot_venue_hallsupportscategory_hallsupportsslot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hallsupportsslot",
            old_name="hall_id",
            new_name="hall",
        ),
        migrations.RenameField(
            model_name="hallsupportsslot",
            old_name="slot_id",
            new_name="slot",
        ),
        migrations.AddField(
            model_name="hall",
            name="slot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="hall_manager.slot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hall",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="hall_manager.venue",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="seat_type",
            field=models.CharField(default="CLASSIC", max_length=10),
            preserve_default=False,
        ),
    ]
