# Generated by Django 5.1.2 on 2024-11-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hall_manager", "0004_rename_hall_id_hallsupportsslot_hall_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hallsupportscategory",
            name="hall_id",
        ),
        migrations.AddField(
            model_name="hallsupportscategory",
            name="hall",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hallSupportsCategories",
                to="hall_manager.hall",
            ),
        ),
        migrations.AlterField(
            model_name="hallsupportsslot",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hallSupportsSlots",
                to="hall_manager.hall",
            ),
        ),
        migrations.AlterField(
            model_name="hallsupportsslot",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hallSupportsSlots",
                to="hall_manager.slot",
            ),
        ),
    ]
