# Generated by Django 5.1.2 on 2024-11-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_manager', '0005_remove_hallsupportscategory_hall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='hall_manager.slot'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='hall_manager.venue'),
        ),
    ]
