# Generated by Django 5.1.2 on 2024-11-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hall_manager", "0007_rename_seatnumber_seat_seat_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="seat_type",
        ),
    ]
