# Generated by Django 5.1.2 on 2024-11-13 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_manager', '0008_remove_seat_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='slot',
        ),
        migrations.AlterField(
            model_name='hallsupportscategory',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hall_supports_categories', to='hall_manager.hall'),
        ),
        migrations.AlterField(
            model_name='hallsupportsslot',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_supports_slots', to='hall_manager.hall'),
        ),
        migrations.AlterField(
            model_name='hallsupportsslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_supports_slots', to='hall_manager.slot'),
        ),
    ]
