# Generated by Django 5.1.2 on 2024-11-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hall_manager",
            "0009_remove_hall_slot_alter_hallsupportscategory_hall_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="hallsupportscategory",
            name="show_category",
        ),
        migrations.AlterField(
            model_name="hallsupportsslot",
            name="hall",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hall_supports_slots",
                to="hall_manager.hall",
            ),
        ),
        migrations.AlterField(
            model_name="hallsupportsslot",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hall_supports_slots",
                to="hall_manager.slot",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="hall",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="hall_manager.hall",
            ),
        ),
        migrations.AddField(
            model_name="hallsupportscategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hall_supports_categories",
                to="hall_manager.category",
            ),
        ),
    ]
