# Generated by Django 5.1.2 on 2024-11-10 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall_manager', '0002_seat'),
        ('show_manager', '0002_alter_show_category_alter_show_status'),
        ('users', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCancelled', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.customer')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hall_manager.hall')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='hall_manager.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='show_manager.show')),
            ],
        ),
    ]
