# Generated by Django 5.1.2 on 2024-11-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerLoyalty',
        ),
    ]
